# Generated by Django 2.2.8 on 2020-11-02 04:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size_color',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
