# Generated by Django 2.2.8 on 2020-10-15 03:39

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('BrandsName', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.PositiveIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_user', models.PositiveIntegerField(blank=True, null=True)),
                ('deleted', models.DateTimeField(auto_now=True, null=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Brandscreateuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categlory',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('CategloryName', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.PositiveIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_user', models.PositiveIntegerField(blank=True, null=True)),
                ('deleted', models.DateTimeField(auto_now=True, null=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Categlorycreateuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('ColorsName', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.PositiveIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_user', models.PositiveIntegerField(blank=True, null=True)),
                ('deleted', models.DateTimeField(auto_now=True, null=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Colorscreateuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('MaterialName', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.PositiveIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_user', models.PositiveIntegerField(blank=True, null=True)),
                ('deleted', models.DateTimeField(auto_now=True, null=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Materialcreateuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('Image', models.ImageField(max_length=254, upload_to='product_image/')),
                ('Product_Name', models.CharField(max_length=1000)),
                ('Product_Description', models.CharField(max_length=1000)),
                ('Price', models.IntegerField()),
                ('Discount_Price', models.IntegerField(default=0)),
                ('Availability', models.PositiveIntegerField(default=0)),
                ('New_Arrivals', models.BooleanField(default=0, null=True)),
                ('Deals_of_day', models.BooleanField(default=0, null=True)),
                ('Coming_soon', models.BooleanField(default=0, null=True)),
                ('Courier_charge', models.CharField(max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.PositiveIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('Product_Brands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_Brandsuser', to='accounts.Brands')),
                ('Product_Categlory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_Categloryuser', to='accounts.Categlory')),
                ('Product_Colors', models.ManyToManyField(related_name='Product_Colorsuser', to='accounts.Colors')),
            ],
        ),
        migrations.CreateModel(
            name='Send_message',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=10000)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='User_Wishlist',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.PositiveIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductWishlist', to='accounts.Product')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wishcreated_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Address',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('landmark', models.CharField(max_length=2500)),
                ('address', models.CharField(max_length=2500)),
                ('country', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('pincode', models.CharField(default='43701', max_length=10)),
                ('default', models.BooleanField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.PositiveIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserAddress_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('Product_Size', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.PositiveIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_user', models.PositiveIntegerField(blank=True, null=True)),
                ('deleted', models.DateTimeField(auto_now=True, null=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sizecreateuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True)),
                ('otp', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('cart', models.TextField(null=True)),
                ('profile_pic', models.ImageField(default='profile.png', null=True, upload_to='media/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Product_fliters',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=10000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.PositiveIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('Categlory', models.ManyToManyField(related_name='Categlory_Colorsuser', to='accounts.Categlory')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_flitersss', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentsss', to='accounts.Product_fliters')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Product_Description',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('Product_Description', models.CharField(max_length=10000)),
                ('Manufacturing', models.CharField(max_length=10000)),
                ('Weight', models.FloatField()),
                ('Matrial_detail', models.CharField(max_length=10000)),
                ('Proof', models.CharField(max_length=100)),
                ('Samples', models.CharField(max_length=10000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.PositiveIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductDes', to='accounts.Product')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dcreated_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Filter_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product_Filter_Namesssssss', to='accounts.Product_fliters'),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_Materialss', to='accounts.Material'),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Size',
            field=models.ManyToManyField(related_name='Product_Sizeuser', to='accounts.Size'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sizecreated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('subtotal', models.IntegerField()),
                ('address', models.CharField(max_length=250)),
                ('telephone', models.IntegerField()),
                ('payed', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.PositiveIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_user', to=settings.AUTH_USER_MODEL)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_user', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image_Video',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('Image', models.ImageField(max_length=254, upload_to='product_image/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.PositiveIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_user', models.PositiveIntegerField(blank=True, null=True)),
                ('deleted', models.DateTimeField(auto_now=True, null=True)),
                ('Image_Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Image_Productss', to='accounts.Product')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Image_Video', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=10000)),
                ('answer', models.CharField(max_length=10000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.PositiveIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Faq', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_details',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('phone', models.CharField(max_length=10000)),
                ('hours', models.CharField(max_length=10000)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=10000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.PositiveIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Contact_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='caseback_data_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.PositiveIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casebackdata_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caseback_data_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='caseback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_member', models.IntegerField()),
                ('amount', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.PositiveIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caseback_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(default='profile.png', null=True, upload_to='media/')),
                ('description', models.CharField(max_length=10000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.PositiveIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='About', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
