# Generated by Django 2.2.8 on 2020-10-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_details',
            name='phone2',
            field=models.CharField(default=0, max_length=10000),
            preserve_default=False,
        ),
    ]
