# Generated by Django 2.2.8 on 2020-10-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contact_details_phone2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_wishlist',
            name='Product',
            field=models.CharField(max_length=500),
        ),
    ]
