# Generated by Django 2.2.8 on 2020-11-02 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_auto_20201023_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_address',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('Account_Number', models.CharField(max_length=10000)),
                ('UPI', models.CharField(max_length=10000)),
                ('IFSC', models.CharField(max_length=10000)),
                ('Contact_Number', models.CharField(max_length=1000)),
                ('Created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Account_address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
