# Generated by Django 2.2.8 on 2020-10-15 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categlory',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('CategloryName', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.PositiveIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_user', models.PositiveIntegerField(blank=True, null=True)),
                ('deleted', models.DateTimeField(auto_now=True, null=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Categlorygiftcreateuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('Image', models.ImageField(max_length=254, upload_to='product_image/')),
                ('Product_Name', models.CharField(max_length=1000)),
                ('Product_Description', models.CharField(max_length=1000)),
                ('Price', models.IntegerField()),
                ('Discount_Price', models.IntegerField(default=0)),
                ('Availability', models.PositiveIntegerField(default=0)),
                ('New_Arrivals', models.BooleanField(default=0, null=True)),
                ('Deals_of_day', models.BooleanField(default=0, null=True)),
                ('Coming_soon', models.BooleanField(default=0, null=True)),
                ('Courier_charge', models.CharField(max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.PositiveIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('Product_Categlory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giftProduct_Categloryuser', to='gift.Categlory')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('BrandsName', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.PositiveIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_user', models.PositiveIntegerField(blank=True, null=True)),
                ('deleted', models.DateTimeField(auto_now=True, null=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Brandsgiftcreateuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product_fliters',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=10000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.PositiveIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('Categlory', models.ManyToManyField(related_name='giftCateglory_Colorsuser', to='gift.Categlory')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giftProduct_flitersss', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='giftparentsss', to='gift.Product_fliters')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Product_Description',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('Product_Description', models.CharField(max_length=10000)),
                ('Manufacturing', models.CharField(max_length=10000)),
                ('Weight', models.FloatField()),
                ('Matrial_detail', models.CharField(max_length=10000)),
                ('Proof', models.CharField(max_length=100)),
                ('Samples', models.CharField(max_length=10000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.PositiveIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductDes', to='gift.Product')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giftDcreated_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Filter_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product_Filter_Namesssssss', to='gift.Product_fliters'),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giftProduct_Brandsuser', to='gift.Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giftSizecreated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Image_Video',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('Image', models.ImageField(max_length=254, upload_to='product_image/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.PositiveIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_user', models.PositiveIntegerField(blank=True, null=True)),
                ('deleted', models.DateTimeField(auto_now=True, null=True)),
                ('Image_Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giftImage_Productss', to='gift.Product')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giftImage_Video', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
