# Generated by Django 2.2.8 on 2020-11-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0002_product_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_Colors',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
